### ISSUE TITLE
Implement Vision Transformer (ViT)

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [FrancescoSaverioZuppichini/glasses#187]
### Paper
Implement ViT proposed in [AN IMAGE IS WORTH 16X16 WORDS: TRANSFORMERS FOR IMAGE RECOGNITION AT SCALE](https://arxiv.org/pdf/2010.11929.pdf)
### TODOs
- [x] develop the model in a scalable way (using `*Block` syntax and `nn` modules)
- [ ] draw the model on figma -> used the pictures from the paper
- [x] write doc 
- [x] test the model 
- [x] get (if possible) the pretrained weights
    - [ ] DONE, need to upload them
