### ISSUE TITLE
ResNeSt

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [FrancescoSaverioZuppichini/glasses#198]
### Paper
Implement [ResNeSt: Split-Attention Networks](https://arxiv.org/pdf/2004.08955.pdf)
### TODOs
- [x] develop the model in a scalable way (using `*Block` syntax and `nn` modules)
- [ ] draw the model on figma
- [x] write doc 
- [x] test the model 
- [ ] get (if possible) the pretrained weights

**Comment by FrancescoSaverioZuppichini** [comment]
Done with #198 missing pretrained weights, will do for now
