### ISSUE TITLE
Drop Block

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [FrancescoSaverioZuppichini/glasses#200]
### Paper
Implement Drop Block proposed [DropBlock: A regularization method for convolutional networks](https://arxiv.org/abs/1810.12890)

### TODOs
- [x] develop the model in a scalable way (using `*Block` syntax and `nn` modules)
- [x] draw the model on figma
- [x] write doc 
- [x] test the model

**Comment by FrancescoSaverioZuppichini** [comment]
Close by #199
