### ISSUE TITLE
DeiT

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [FrancescoSaverioZuppichini/glasses#201]
### Paper
Implement [Training data-efficient image transformers & distillation through attention](https://arxiv.org/abs/2012.12877)

Very easy, see https://github.com/facebookresearch/deit/blob/main/models.py
### TODOs
- [x] develop the model in a scalable way (using `*Block` syntax and `nn` modules)
- [x] draw the model on figma
- [x] write doc 
- [x] test the model 
- [x] get (if possible) the pretrained weights
