### ISSUE TITLE
DenseNet

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [FrancescoSaverioZuppichini/glasses#22]
### Paper
Implement [DenseNet](https://arxiv.org/abs/1608.06993)
### TODOs
- [x] develop the model in a scalable way (using `*Block` syntax and `nn` modules)
- [x] draw the model on figma
- [x] write doc 
- [x] get (if possible) the pretrained weights
- [x] test the model

**Comment by FrancescoSaverioZuppichini** [comment]
Missing one Densenet model (I think is 264)

**Comment by FrancescoSaverioZuppichini** [comment]
Done!

**Comment by FrancescoSaverioZuppichini** [comment]
Missing init
https://github.com/pytorch/vision/blob/10d5a55c332771164c13375f445331c52f8de6f1/torchvision/models/densenet.py#L182

**Comment by FrancescoSaverioZuppichini** [comment]
Outputs with torchvision's model do not match
