### ISSUE TITLE
Unet

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [FrancescoSaverioZuppichini/glasses#62]
### Paper
Develop [Unet](https://arxiv.org/abs/1505.04597)
### TODOs
- [x] develop the model in a scalable way (using `*Block` syntax and `nn` modules)
- [x] draw the model on figma
- [x] write doc 
- [x] test the model 
- [ ] get (if possible) the pretrained weights
