### ISSUE TITLE
Squeeze and Excitation

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [FrancescoSaverioZuppichini/glasses#64]
### Paper
Develop Squeeze and Excitation and the relative networks proposed in [Squeeze-and-Excitation Networks](https://arxiv.org/abs/1709.01507)
### TODOs
- [x] develop the model in a scalable way (using `*Block` syntax and `nn` modules)
- [ ] draw the model on figma
- [ ] write doc 
- [x] test the model 
- [ ] get (if possible) the pretrained weights
