### ISSUE TITLE
MobileNet v2

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [FrancescoSaverioZuppichini/glasses#74]
### Paper
Implement [MobileNet v2](https://arxiv.org/pdf/1801.04381.pdf)
### TODOs
- [x] develop the model in a scalable way (using `*Block` syntax and `nn` modules)
- [x] draw the model on figma
- [x] write doc 
- [x] test the model 
- [x] get (if possible) the pretrained weights
