### ISSUE TITLE
Concurrent Spatial and Channel SE

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [FrancescoSaverioZuppichini/glasses#91]
### Paper
Implement SE version from [Concurrent Spatial and Channel ‘Squeeze &
Excitation’ in Fully Convolutional Networks](https://arxiv.org/pdf/1803.02579.pdf) 
### TODOs
- [x] develop the model in a scalable way (using `*Block` syntax and `nn` modules)
- [x] draw the model on figma
- [x] write doc 
- [x] test the model 
- [x] get (if possible) the pretrained weights

**Comment by FrancescoSaverioZuppichini** [comment]
done with #94
